# Generated by Django 3.0.8 on 2020-07-26 08:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Review_data',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nickname', models.CharField(max_length=20)),
                ('date', models.CharField(max_length=30)),
                ('rating', models.IntegerField()),
                ('comment', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Review_Classfiy',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('user_id', models.CharField(max_length=30)),
                ('classify', models.CharField(max_length=20)),
                ('release_date', models.DateField()),
                ('reivew_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='classify.Review_data')),
            ],
        ),
    ]
