# Generated by Django 3.0.8 on 2020-07-26 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classify', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review_data',
            name='comment',
            field=models.TextField(blank=True),
        ),
    ]
