# Generated by Django 3.0.8 on 2020-07-31 03:08

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('classify', '0003_auto_20200726_1727'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review_classfiy',
            name='user_id',
        ),
        migrations.AddField(
            model_name='review_classfiy',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='review_classfiy',
            name='classify',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='review_classfiy',
            name='release_date',
            field=models.DateField(default=datetime.datetime(2020, 7, 31, 3, 8, 15, 243739, tzinfo=utc)),
        ),
    ]
