# Generated by Django 3.0.8 on 2020-07-31 03:08

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('classify', '0004_auto_20200731_1208'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review_classfiy',
            old_name='reivew_id',
            new_name='review_id',
        ),
        migrations.AlterField(
            model_name='review_classfiy',
            name='release_date',
            field=models.DateField(default=datetime.datetime(2020, 7, 31, 3, 8, 38, 100214, tzinfo=utc)),
        ),
    ]
