# Generated by Django 3.0.8 on 2020-08-28 04:25

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('classify', '0005_auto_20200731_1208'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review_classfiy',
            name='release_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='review_data',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
